export const selectors = {
  webPage: {
    addNewPageButton: '//*[@id="list-WebPage-d41dAddpage"]',
    pageNameInput: '//*[@id="pageName_cs"]',
    contentTemplateSelect: 'select[name="tplcontent"]',
    layoutTemplateSelect: 'select[name="tpllayout"]',
    addAndEditButton: '//*[@id="add_edit_button"]',
    webPageHeading: '//*[@id="WebPage-heading_cs"]',
    approveSelect: '//*[@id="WebPage-approved_cs"]',
    deleteButton: (name: string) => `//*[contains(text(),${name})]/following::*[@id="delete"]`,
    toTrashButton: (name: string) => `//*[contains(text(),${name})]/following::*[@id="totrash"]`,
    deleteConfirmButton: '//*[@id="buttonConfirm"]',
    toTrashConfirmButton: '//*[contains (@class, "success ui-button")]',
    searchInput: '//*[contains (@class, "inputSearch")]',
    getCubeById: (id: string) => `//*[@id="${id}"]`,
    getRow: (index: number) => `(//*[@data-element-template="element_ROW"])[${index}]`,
    topPlus: '//*[@id="addtop"]',
    centrePlus: '//*[@id="addcenter"]',
    containers: '//*[contains(@class, "container__wrapper")]/div'
  },
  components: {
    headingEnable: '#heading_enable-box span label', // predelat
    headingValue: '//*[@id="heading_value_cs"]',
    headerInput: '//*[@id="header_cs"]',
    blockTabDefault: '//*[@id="default"]',
    textEditor: '//*[@role="textbox"]',
    componentWindow: '//*[@id="cubepopup"]',
    payButtonTitle: '//*[@id="label_cs"]',
    searchBoxEnabled: '//*[@id="searchBoxEnabled"]',
    filterButtonTextInput: '//*[@id="filterButtonText_cs"]',
    productsIdsInput: '//*[@id="productsids"]',
    //userNameRadio: '//*[@value="firstname"]',
    // ctaEnabled: '//*[@id="ctaEnabled"]',
    // ctaTextCs: '//*[@id="ctaText_cs"]',
    //headerSelect: '//*[@id="headerId"]',
    //cubeEdit: '//*[@data-test="constructer-edit-component"]', //TODO
    // getTextBlockInRow: (index: number) => `//div[@data-ebr-template-type="block"][${index}]//div[@role="textbox"]`,
    // horizontalLineHeight: '//*[@id="height"]',
    // horizontalSpaceSize: '//*[@id="gapSize"]',
    // anchorNameInput: '//*[@id="achor_id"]',
    titleCs: '//*[@id="title_cs"]',
    //slideshowTitle: '//*[@id="title-1_cs"]',
    // title: '//*[@id="title"]',
    // blockTabDisplay: '//*[@id="display"]',
    sourceCodeTextArea: '//*[@id="sourcecode"]',
    buttonTextInFilterOfProducts: '//*[@id="filterButtonText_cs"]',
    // productsIds: '//*[@id="productsids"]',
  },
  layoutTemplate: {
    finishCheckboxLayout: '#WebTpllayout-isFinished-box span label',
    finishCheckboxContent: '#WebTplcontent-isFinished-box span label',
    finishCheckboxHeader: '#WebHeaders-isFinished-box span label',
    finishCheckboxForm: '#WebForms-isFinished-box span label',
    rowEdit: '//*[@id="btnWebTemplateEdit"]',
    rowEditClose: '//*[@id="btnWebTemplateComposer"]',
    codeTextArea: '//*[@id="WebTpllayout-desktopContent"]',
  },
  // common: {
  //   saveButton: 'a:has-text("Uložit")',
  //   deleteButton: 'button:has-text("Odstranit")',
  //   deleteIcon: 'a[title="Smazat"]',
  //   confirmButton: 'button:has-text("Potvrdit")',
  // },
  PathUrlAddresses: {
    webPage: '/web/page',
    auth: '/core/auth',
    webPageEdit: '/web/page/edit/pk',
    layoutTemplates: '/web/tpllayout',
    contentTemplates: '/web/tplcontent',
    headerTemplates: '/web/headers',
    formTemplates: '/web/forms'
  }
} as const;
